# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    weird_authenticator:
        class: AppBundle\Security\WeirdFormLoginAuthenticator
        autowire: true